### ISSUE TITLE
Issue with Denver 3.0 Boarding House version

### ISSUE THREAD

**Issue by mycroftjr** [whitebalverines/NPC-Denver#1]
```
[22:22:15 ERROR Content Patcher] Unhandled exception applying patch: Denver > EditMap Maps/Custom_BoardingHouse_BoardingHouse.
StardewModdingAPI.Framework.Exceptions.SContentLoadException: Denver loaded map 'assets/Maps/BoardingHouseDenver.tmx' with invalid tilesheet path 'InsideTiles.png'. The tilesheet couldn't be found relative to either map file or the game's content folder.
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.FixTilesheetPaths(Map map, String relativeMapPath, Boolean fixEagerPathPrefixes) in E:\source\_Stardew\SMAPI\src\SMAPI\Framework\ContentManagers\ModContentManager.cs:line 438
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadMapFile[T](IAssetName assetName, FileInfo file) in E:\source\_Stardew\SMAPI\src\SMAPI\Framework\ContentManagers\ModContentManager.cs:line 294
   at StardewModdingAPI.Framework.ContentManagers.ModContentManager.LoadExact[T](IAssetName assetName, Boolean useCache) in E:\source\_Stardew\SMAPI\src\SMAPI\Framework\ContentManagers\ModContentManager.cs:line 134
   at StardewModdingAPI.Framework.ModHelpers.ModContentHelper.Load[T](String relativePath) in E:\source\_Stardew\SMAPI\src\SMAPI\Framework\ModHelpers\ModContentHelper.cs:line 57
   at ContentPatcher.Framework.Patches.EditMapPatch.Edit[T](IAssetData asset) in E:\source\_Stardew\Mods.Pathoschild\ContentPatcher\Framework\Patches\EditMapPatch.cs:line 129
   at ContentPatcher.Framework.PatchManager.ApplyEdits[T](ICollection`1 patches, IAssetData asset) in E:\source\_Stardew\Mods.Pathoschild\ContentPatcher\Framework\PatchManager.cs:line 548
```
InsideTiles.png being from `Boarding House\[CP] Boarding House\assets\Maps`. So I guess it's probably not being imported properly? I haven't made any TMX files before, but https://stardewvalleywiki.com/Modding:Maps#Adding_tilesets may help?

In the meantime, copying that image into `[NPC] Denver\[CP] Denver\assets\Maps` seems to work as a workaround for the end user, although I'm aware that you as a mod author probably can't/shouldn't redistribute that image.

**Comment by whitebalverines** [comment]
Thanks for the heads up! This is why i released it on github before nexus
lol, i may have missed a few things

**Comment by mycroftjr** [comment]
> Thanks for the heads up! This is why i released it on github before nexus lol, i may have missed a few things

No problem, I didn't expect it to be working perfectly yet lol (given the lack of Nexus publishing), I'm just excited that the Nexus update is (probably) coming soon
I'm available most nights to test mods if you need help testing any fixes?
